### ISSUE TITLE
Any plans for 'testing' builds?

### ISSUE THREAD

**Issue by jacob414** [rocjs/roc#102]
Hello!

Very nice project! Already evaluating it for the creation of a new app.

I'm planning to use it in an environment that wants a high degree of  TDD, though. Are there plans for separate production/testing builds? I'm experimenting [here](https://github.com/Plexical/roc-0), e.g. attempting to install Mocha.js, but I'm also curious if something along the lines of that is already on the roadmap.

/Jacob

**Comment by dlmr** [comment]
Hi!

Awesome to hear!

We are experimenting with this at [roc-plugin-test-mocha-karma-webpack](https://github.com/rocjs/roc-plugin-test-mocha-karma-webpack/). This focuses on code that can run in a client context and we definitely what to add a simple way to support Node testing as well. Please test it out and see if it might be what you are looking for.

**Comment by dlmr** [comment]
[You can see here how you add it to your project.](https://medium.com/@DZV/roc-one-solution-to-javascript-fatigue-b14ea07b9763#15c0)

**Comment by jacob414** [comment]
Ops, missed that so far. Will check it out immediately, thanks!
