### ISSUE TITLE
Escape hatch for settings

### ISSUE THREAD

**Issue by dlmr** [rocjs/roc#103]
We need a way to easily go around how Roc extensions interact with other libraries. This since they might limit both extension and application developers.
### Let's look at an example

Say that we have an extension that uses [koa-static](https://github.com/koajs/static) and that extension has provided a way through settings to define [`maxage`](https://github.com/koajs/static#options). This is all good and well until someone needs to also disable [`gzip`](https://github.com/koajs/static#options) for instance. 

Without an escape hatch the user would have the following alternatives.
- Create a PR that adds the needed option.
- Create an issue that requests the needed option.
- Create some workaround through some less fitting API, maybe reimplementing all of the middlewares that is defined by the extension and using the option.
- Gives up and stops using Roc.

One argument against this escape hatch is that the extension developer should just have mapped all possible options from the beginning. I do not however believe that is optimal for two reasons.  
1. This would create a lot of noise in our documentation / CLI. Roc should focus on the most common things, not map up everything imaginable. 
2. An dependency might be updated adding a new option without the extension developer noticing.

The reason that we need to manage this at all is to not give incorrect feedback to the end user. This since we want to inform the user if they have misspelled a setting option or maybe that one has been removed between different versions of a extension. This would not be possible if we allowed anything in our `roc.config.js` files.
### How should this escape hatch look

Currently I see two different options, both with their pros and cons.
#### `escape` function

The idea is that `roc` exports a function that can be used to wrap an object that we want to enable to be used as an escape hatch.

``` js
koaStatic: escape({
  maxage: 60
})
```

This would create a special object that Roc knows can be used as an escape hatch. It will still be possible to set this through the CLI and define _meta_ data for the option, that is _validation_ and _descriptions_. Then the user can do the following.

```
koaStatic: {
  maxage: 600,
  gzip: false
}
```

We would know that this should be allowed and we will not warn the user about this. Potentially we could give some other type of feedback (not a warning), since we do not know that `gzip` in this case actually will be managed correctly. It would of course also not be possible to set a value for `gzip` through the CLI.

This leads me to an extension to this solution.

``` js
koaStatic: escape({
  maxage: 60
}, ['gzip'])
```

Here we have used an array to inform `roc` that the listed properties should be fully allowed and not question the user, we know that `gzip` is a possible value. The benefit of this is that we can define what settings that is possible to define but still not need to manage everything through Roc.

A disadvantage(?) of this approach is that the user can't override things that the extension has defined. Take `maxage` as an example, say that the validation requires it to be a number but also a boolean is allowed. There would here be no way to go around this error by the extensions developer. Another potential problem is that some user might use a property through a escape hatch and later we update the extension and add validation for it. This could lead to the settings not any longer being valid because the validation is more strict than what the library accepts.

One could argue that if the validation is incorrect that is clearly a bug in the extension and something that should be fixed, creating way to go around it might be bad. See the other alternative for more about this.
##### Pro
- Makes it possible to "promote" an option to a managed option without any user interaction
- Great feedback to the user
- Natural way to generate documentation about what settings that has escape hatches enabled
##### Cons
- Makes it possible to "promote" an option to a managed option without any user interaction
- Not possible to override "managed" options
#### `escape` property

A really simple solution would be to create a special property that can be used by extensions to manage settings outside of the Roc scope.

``` js
// This would be as before
koaStatic: {
  maxage: 60
}
```

And in the application.

```
koaStatic: {
  maxage: 600,
  __escape: {
    gzip: false
  }
}
```

This would make it trivial to define options not defined by the extension and also make it possible to override potential mistakes in a extension. The `__escape` property would have the highest priority.

However this solution would not give us any form of validation and it might encourage user to use this `__escape` property for everything. This could be bad since it would override CLI options and not benefit of validation from `roc`. 
##### Pro
- Possible to override developer mistakes
- Simple implementation
##### Cons
- Not getting any validation benefits
- Might be confusing for others that it's not possible to override something with the CLI
### Conclusion

This issue became much longer than I would have liked but I think we will benefit greatly from a good pattern here. So my questions is; what alternative do you like the most and is there one that might be even better than what I have listed here?

**Comment by lizell** [comment]
I'm all for simple and easy to understand implementations and it seems like the main thing at stake here is validation. I would argue that one could issue a warning if someone is trying to override an escaped option via CLI and also in verbose mode inform the user about that no validation is performed for the escaped property.

When it comes to naming, is `escape` really the correct word for this? I'm thinking more in terms of `override` or maybe `raw`?

I also see need for these settings as something I would do waiting for my PR to be accepted, since if the setting is needed, it would probably be part of the original extension eventually. Of course there will be less commonly used settings that will never make it in the extension, but then I would have to know what I'm doing setting it (making the need of validation less important IMO).

**Comment by dlmr** [comment]
The name `escape` is terrible yes and was only used temporarily! I do like `override`, describes the purpose quite well.
