### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by dlmr** [rocjs/roc#11]
We are pretty close for this to be stable and feature complete enough to release version 1.0. 

**The things that needs to be taken care of is the following in my opinion.**
- [x] Implement a way to generate documentation for the configuration in HTML, Markdown and for the CLI. Solved by #12 
- [x] Validate configuration structure to make sure that a user has not by mistake put values in the wrong place.
- [x] Implement more tests to get a better coverage and make updates and changes in the future easier.
- [x] Go over the documentation and make sure that it's up to date and relevant.

Additionally I believe we should do some refactoring and splitting of functionality in the CLI part of Roc giving the need for the following functionality in `roc-config`.
- [x] Parse a `process.argv` object to a roc configuration object.

Anything to add here @andreasrs?

**Comment by andreasrs** [comment]
I think we should also review the current use of globals for storing the configuration state. I think we ended up doing it because of the configuration having to be active across instances that do not share require cache. 

This is the only current use of globals outside of Webpack defineplugin usage afaik. Only the configuration module itself should be able to modify the configuration state and this is not currently the case.

**Comment by dlmr** [comment]
I'm open for suggestions on how to solve it in another way. Currently we use them to make sure that it works when we include `roc-config` both in an extension and in the CLI. 

It could be solved to some extent by having a way to init `roc-config` or use environment variables to do the same, however that changes nothing really since they are globals.

I do not think globals is that bad here, they are still just used to find the default configuration object/path that then can be extended.

**Comment by dlmr** [comment]
Should it be possible to create a new configuration group on an application level? 

This can be useful as a way to use Roc for configuring some things in the application, most notably when using custom Koa middlewares since they will receive the configuration object. 

Or should we suggest against this and instead let the user use `/config` for application level configuration to avoid potential conflicts between extensions and applications? 

Thoughts on this @andreasrs?

**Comment by dlmr** [comment]
This is the suggested format on the configuration files when 1.0 lands.

**roc.config.js**

``` js
module.exports = {
    config: {
        // Same as before
        // ...
    },
   // Commands that is exposed from the extension
    commands: {
        build: require('../cli/build'),
        // configurationObject - Contains the merged and final configuration
        dev: (configurationObject, commandOptions, extraArguments) => { // do something… }
    },
    // Plugins is way to override, extend and enhance internal aspects of extensions without having to override an entire command.
    // The names and what is exported is entirely up to the consuming extension, no protection for name clashes.
    plugins: {
        createBuilder: {
            someName: require('../builder')
        }
    }
};
```

**roc.config.meta.js**

``` js
const isPath = require('roc-config/validators').isPath;

module.exports = {
    config: {
        descriptions: {
            // ...
        },
        validations: {
            // ...
        }
    },
    commands: {
        // As will all data inside of meta; this should be optional and it will work without it
        build: {
            // This array will note what config groups that should be displayed / can be used with the command
            // By setting this to true or an array makes the command parse roc-config params
            config: ['build'],
            // Description for the command, will be used when using help for the command.
            description: 'Build the current project.',
            // By default a command will just run if nothing is added here, that is we do not know how to run it!
            // Order matters!
            // When writing help it will print it as [optional] <required>
            options: [{
                name: 'repository',
                required: true,
                validation: isPath
            }]

        }
    },
    // If a description it will be used to document it.
    plugins: {
        createBuilder: 'Some description on what this is and what is does'
    }
};
```

**Comment by dlmr** [comment]
This changes makes it natural that we drop the `roc` key in `package.json` since it the actual dependencies will manage what "cli" that the project uses. The global/general cli will in this change only manage non-project specific commands like `init`.

What we still could do however is to verify the version against the the latest and inform if there is a new version available. This should be done after 1.0 lands I think.

**Comment by dlmr** [comment]
Changing the `config` key in the `roc.config(.meta).js` to `settings` to make more sense.
