### ISSUE TITLE
Incorrect links in generated documentation

### ISSUE THREAD

**Issue by PAkerstrand** [rocjs/roc#121]
It seems like the links in `README.md` for `next`-version are generated incorrectly. You get links like: `https://github.com/docs/Actions` rather than `https://github.com/rocjs/roc-abstract-plugin-test/blob/next/extensions/roc-abstract-plugin-test/docs/Commands.md`. If you view the raw markdown, it looks like this:

``` md
## Documentation
- [Actions](/docs/Actions)
- [Commands](/docs/Commands)
```

rather than

``` md
## Documentation
- [Actions](docs/Actions)
- [Commands](docs/Commands)
```

**Comment by dlmr** [comment]
Thanks, this has now been corrected in  62ba0e8.
