### ISSUE TITLE
Issue with async calls - HERE maps, but might be also present in different situations

### ISSUE THREAD

**Issue by konradzuwala** [rocjs/roc#122]
Hello!
I recently found an issue which seems for me to be ROC related.
Consider such component:

``` javascript
import React from 'react';
import $ from 'jquery';
import styles from './style.scss';

export default class MapView extends React.Component {
    initializeMap() {
    var platform = new H.service.Platform({
      'app_id': 'replace with your app id',
      'app_code': 'replace with your app code',
      'useHTTPS': true
    });
    // Create map with default layers (the usual city map)
    var defaultLayers = platform.createDefaultLayers();

    // Create map object in element with #map-container
    // save it as global!

    console.log(document.getElementById('map-container'));
    var map = new H.Map(
      document.getElementById('map-container'),
      defaultLayers.normal.map,
      {
          zoom: 6,
          center: { lat: 55.7, lng: 12.4 }
      });
      console.log(map);
    let markers = new H.map.Group();
    map.addObject(markers);

    this.setState({
      map: map,
      markers: markers
    }, function() {
      this.fetchDataFromApi();
    }.bind(this));
  }

  fetchDataFromApi() {
      console.log("fetching")
      $.get('http://192.168.1.32:5000/vehicles', function(result) {
      this.setState({vehicles: JSON.parse(result)}, function() {
        console.log('fetched');
        this.redraw();

      }.bind(this));
    }.bind(this));
  }

  componentDidMount() {
      console.log("mounted")
      this.initializeMap();
  }

  redraw() {
      var vehicles = this.state.vehicles;
      this.drawVehicles(vehicles);
  }

  drawVehicles(vehicles) {
    var map = this.state.map;
    var parisMarker = new H.map.Marker({ lat: 55.560789, lng: 12.981141 }); // should be taken from API, but for demo purpouse can be hardcoded
    map.addObject(parisMarker); 
  }

  render() {
      console.log("aaa");
    return (
      <div className={ styles.container }>
        <div id="map-container" className={ styles.map }>
        </div>
      </div>
    );
  }
}
```

Now, the code works with webpack, it works if I make a 'plain' react without any build system, it also works in plain JS/HTML5, without any frameworks such as react. But with ROC it gives a weird exception on map.AddObject - InvalidArgument 0. If I put a JSON into JS file and read it, without any jquery/isomporhic fetch, it works totally fine!!! But as soon as I make an async call, there is some problem. As I wrote before, I tested this code with webpack and was OK, so the issue must be somewhere in ROC - maybe with dev server?

**Comment by dlmr** [comment]
Hi!

Hard to tell what this could be based on the information that you have provided. 

If this only happens in Roc it might be because of server rendering that is enabled by default. This error that you see, does it show in the console from which you start the application or the browser that you access it from?

**Comment by konradzuwala** [comment]
The error is showing in browser. I do roc build && roc start, then I go to localhost:4200. The bug happens in all browsers I use. What is funny, sometimes, when I do hot-reload (like I change a file), the marker is shown in correct place on map. I can provide you the code for component if it is needed. But the code is very simple and, like I said, webpack and plain react work fine. How do I disable server rendering? I can check out if it solves the issue

**Comment by dlmr** [comment]
By using `roc build && roc start` you are starting it in production mode, so if the error happens there it should not be related to development in any way, like the dev server or hot reloading.

Use `roc dev` for starting in development mode with support of these things.

You can disable the server side rendering by starting the application, either in development mode or production, and using this flag: `--ssr false`. 

That means that you would do `roc dev --ssr false` to start the application in development mode with server sider rendering disabled.

**Comment by konradzuwala** [comment]
OK, so the bug is present in production, as like you said, i do a production start. What is funny, it happens only with asyncs. Like I wrote, using json inside .js file, sth like: let data = ..., markers are added properly to map, no exception is being thrown. I tried jquery, isomporhic fetch and 'normal' fetch. Webpack - all ok, ROC same exception thrown. Is there any way I could debug what is going on there, to provide you as much info as possible? Right now the only solution we see is migration to webpack, but it is a bit tricky :)

**Comment by dlmr** [comment]
The best thing would be if you have the application running somewhere on a server with a URL that I quickly could check out or alternatively a minimal repo that I could look that have this error.

**Comment by konradzuwala** [comment]
Sure, I can ZIP you my repo, would it be OK? I wouldn't like to put it to github, as there are my private credentials for maps :)

**Comment by dlmr** [comment]
That works but it would be optimal with a git repo 👍

**Comment by konradzuwala** [comment]
OK, can I send you credentials in private?

**Comment by dlmr** [comment]
Yes, I think the easiest would be to add me on Twitter and send me a DM. https://twitter.com/dzv

**Comment by konradzuwala** [comment]
OK doing. Thank you for support :)

**Comment by konradzuwala** [comment]
Here is the repo: https://github.com/konradzuwala/rocjs_demo 
As for Twitter, doing now :)

**Comment by konradzuwala** [comment]
Seems I cannot send you DM if you're not observing me :)

**Comment by konradzuwala** [comment]
Hello, were you able to reproduce the bug?

**Comment by dlmr** [comment]
Yes, I will look more into this as soon as possible. Thanks again for the bug report.

**Comment by konradzuwala** [comment]
Cool, if you need some help please let me know :)

**Comment by konradzuwala** [comment]
Hello, how is it going here?:) Need any help?

**Comment by konradzuwala** [comment]
Hello, hello :) Have you maybe found someone? We are quite blocked by the issue in the project, so if you don't have time, we might have a look at it. However, do you know what place is buggy, so we know where to start looking? Thx!

**Comment by dlmr** [comment]
I have now had the chance to look a little closer at this problem and I think I know that is happening. 

Seems like the problem happens because we are using React Helmet and specifically this issue: https://github.com/nfl/react-helmet/issues/149

A workaround right now is to use a custom template and add the scripts that are needed directly to it. This can be done in the following way.
1. Create a folder named `views` in the root of the project and copy the default template there from here: https://github.com/rocjs/roc-package-web-app-react/blob/alpha/packages/roc-package-web-app-react/views/main.html
2. Add the scripts tag to it as you would do normally. 
3. Add the following to the `roc.config.js`.

``` js
module.exports = {
    settings: {
        runtime: {
            template: {
                path: 'views',
            },
        },
    },
};
```

That should be it and the application should now work as expected. Sorry that it took some time to address this.
