### ISSUE TITLE
register-runtime fall over? webpack related

### ISSUE THREAD

**Issue by detra** [rocjs/roc#125]
## Hooks
- [roc-package-base-dev](#roc-package-base-dev)
  - [after-clean](#after-clean)
  - [before-clean](#before-clean)
  - [run-build-command](#run-build-command)
  - [run-dev-command](#run-dev-command)
- [roc-package-web-app-dev](#roc-package-web-app-dev)
  - [server-started](#server-started)
- [roc-package-webpack-dev](#roc-package-webpack-dev)
  - [build-webpack](#build-webpack)
  - [create-watchers](#create-watchers)
  - [get-webpack-targets](#get-webpack-targets)
- [roc-package-webpack-node-dev](#roc-package-webpack-node-dev)
  - [dev-process-created](#dev-process-created)
- [roc-plugin-assets-images](#roc-plugin-assets-images)
  - [add-image](#add-image)
- [roc-plugin-start](#roc-plugin-start)
  - [get-potential-target](#get-potential-target)
  - [get-resolve-paths](#get-resolve-paths)
  - **[register-runtime](#register-runtime)**
- [roc-plugin-style-css](#roc-plugin-style-css)
  - [add-style](#add-style)

just as it hooks roc-plugin-start : register-runtime,
it bows out with the following error

`Roc runtime has been initialized.
SyntaxError: Unexpected reserved word`

```
`at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (D:\..\my-app\build\server\webpack:\external
at __webpack_require__ (D:\..\my-app\build\server\webpack:\webpack\
at Object.<anonymous> (D:\..\my-app\build\server\webpack:\webpack\`
```

`webpack built cbe9dc7f8e..... in 23027ms`

unclear to whats going on

dt

**Comment by dlmr** [comment]
This usually happens when a non transpiled JavaScript file is included in the project. One reason for this can be that a npm module is not transpiled to ES5, Roc will not transpile code located inside `node_modules`.

Might this be the case here?

**Comment by dlmr** [comment]
Did you manage to solve the issue @detra?
