### ISSUE TITLE
roc dev does not work

### ISSUE THREAD

**Issue by devdavidkarlsson** [rocjs/roc#129]
After creating a new project and "cd-ing" roc dev did not work. Is npm install required before roc dev?

Did not understand dev - Did you mean new

**Comment by dlmr** [comment]
Yes. 

Roc loads additional commands based on the dependencies that you have installed. `npm install` should fix this.

**Comment by dlmr** [comment]
I will go ahead and close this issue. 

If you have additional questions or problems please open another issue! :)
