### ISSUE TITLE
Problems adding Facebook Pixel in Roc

### ISSUE THREAD

**Issue by ghost** [rocjs/roc#146]
Hello, I am using React, Redux, and Roc. I have been using react-helmet for adding script to the header, like a video-player and Google Analytics etc. Everything has worked fine, but when I try to add Facebook Pixel to the header it gives me "Duplicate Pixel ID".

If I understand correctly, the page will render multiple times, and that will mess up Facebook Pixel (but not Google Analytics for some reason).

I also tried to add the script to the DOM after the page had rendered (in componentDidMount). That will remove the error message and the pixel will now work (downloaded Facebook Pixel Helper-plugin in chrome), but if I navigate around the page I will get a warning telling me that Pixel has been activated 3 times and that will give me problems with event tracking.

Can anyone check if they are able to add Facebook Pixel to a page that is using React, Redux, and Roc? Just so I can be sure that Roc is not the problem here. Please tell me how you managed to add it if you are successful, I have spent several hours on this problem, and would like to figure out the problem.

Many thanks!
Bjørn Nicholai

**Comment by ghost** [comment]
It seems I cannot add any labels. Please add "question" or something like that to this issue.

**Comment by dlmr** [comment]
Hi!

I think this is the same problem as in #122 and is caused by [an issue in Helmet](https://github.com/nfl/react-helmet/issues/149). 

Try out the solution mentioned here and see if it works: https://github.com/rocjs/roc/issues/122#issuecomment-254490061

**Comment by dlmr** [comment]
@bne9988 Did you manage to solve the issue?
