### ISSUE TITLE
Accessing Redux store in Roc from non-react component

### ISSUE THREAD

**Issue by konradzuwala** [rocjs/roc#147]
Hello,
is there any way of accessing redux store in non react component with Roc? It seems that Roc hides store creation, so I don't get reference to store to save it in my object. What I would like to achieve is a situation, where my react components modify redux store and non-react ES6 class-object has access to this store, so the logic is in this object - it can use data from store to do something with it. Is this possible with Roc? I wanted to make custom middleware, but it seems I can intercept only actions, not return a pointer to store. Or am I mistaken?

**Comment by dlmr** [comment]
Hi!

Are you creating the "non-react ES6 class-object" from a React component? If so I would say that a good pattern is to make that component a `@connect` component and pass the `store` reference to it using the constructor for instance. 

You can also get a hold of the store reference from a Redux middleware, or are you talking about Koa middlwares?

**Comment by konradzuwala** [comment]
Hey, not really. What I do is a standard ES6 plain class, eg:
class MyLogicClass {
doSomething() {
  Redux.getStore().getState() ...
}
}

Now, in this doSomething method I need to get reference to store, to obtain data from it (state). In my react components I call actions that update store, but I need to process this data in separete logical class. Can it be done that way?

**Comment by dlmr** [comment]
Where is the class instantiated?

**Comment by konradzuwala** [comment]
Here it gets tricky :) I wanted to make it either a singleton or instantiate it in Reducer, to make it live in redux store. The class is intended to follow global application state (some parts of our application change depending on user actions history).

**Comment by dlmr** [comment]
I suggest doing it in the root component of your React application, a place where you have access to the store easily for this type of integration.

However it seems that you want to react to state changes and invoked actions in your applications, this seems to be a good candidate for a Redux middleware. You will get the store as a reference as an argument in the first function.

**Comment by konradzuwala** [comment]
The idea here is that we are building independent right-click context menu system for our application. So, depending on what user clicked/selected before, we generate right-click menu on screen with different options. We decided to make it a plain ES6 module, independent from React, so it could be used also with other frameworks.

EDIT: as for you answer:
const contextMenuReduxMiddleware = store => next => action => {
    if (action !== 'CREATE_MENU') {
        next(action);
    }
}

This is how middleware looks, we have store here. So the idea here would be, when we make the first call to our action, like CREATE_MENU here, we should pass store to the class that is handling this action (so our plain ES6 class) and save reference to it inside the class?

**Comment by konradzuwala** [comment]
EDIT2:
const contextMenuReduxMiddleware = store => next => action => {
    if (action !== 'INIT_CONTEXT_MENU') {
        next(action);
    }
    var menuBuilder = new MenuBuilder();
    menuBuilder.setStore(store);

}

Conceptually of course :)

**Comment by dlmr** [comment]
Based on my understanding on this I would have gone for doing this in the root component but your version would also work since you access to the store there as well. 

Maybe something like this would work?

``` js
import storeShape from 'react-redux/lib/utils/storeShape';

class App extends Component {
  static contextTypes = {
    store: storeShape,
  };

  constructor(props, context) {
    super(props, context);
    // Do something with the store reference 
    const { getState } = context.store;
  }
}
```

**Comment by konradzuwala** [comment]
Also looks nice :) Must think of it, thank you anyway for your help!!!!!!!!!
