### ISSUE TITLE
Problems when running beta plugins

### ISSUE THREAD

**Issue by dorota-jking** [rocjs/roc#152]
Hi! I'm working on a React project with Roc (@version 1.0.0-rc.14) and beta versions of plugins (see package.json below) and yesterday when trying to install on a new machine I ran into unexpected issues. After an **npm install** of fresh project, which goes smoothly with no errors, I get this output in the console when running either **roc dev** or **roc build**:

> Found a local version of Roc, will use that over the global one. 
> 
> 
> /Users/dorota/Documents/git/roc-project/node_modules/resolve/lib/sync.js:33
>     throw new Error("Cannot find module '" + x + "' from '" + y + "'");
>           ^
> Error: Cannot find module 'react/lib/EventPluginHub' from '/Users/dorota/Documents/git/roc-project/node_modules/roc-plugin-react'
>     at Function.module.exports [as sync] (/Users/dorota/Documents/git/roc-project/node_modules/resolve/lib/sync.js:33:11)
>     at resolveRequestHelper (/Users/dorota/Documents/git/roc-project/node_modules/roc/src/require/resolveRequest.js:68:30)
>     at RocExportPlugin.resolveRequest (/Users/dorota/Documents/git/roc-project/node_modules/roc/src/require/resolveRequest.js:79:21)
>     at compiler.resolvers.normal.resolve.err (/Users/dorota/Documents/git/roc-project/node_modules/roc-package-webpack-dev/src/webpack/utils/rocExportWebpackPlugin.js:51:40)
>     at /Users/dorota/Documents/git/roc-project/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
>     at onResolved (/Users/dorota/Documents/git/roc-project/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
>     at innerCallback (/Users/dorota/Documents/git/roc-project/node_modules/enhanced-resolve/lib/Resolver.js:94:11)
>     at loggingCallbackWrapper (/Users/dorota/Documents/git/roc-project/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
>     at /Users/dorota/Documents/git/roc-project/node_modules/tapable/lib/Tapable.js:134:6
>     at /Users/dorota/Documents/git/roc-project/node_modules/enhanced-resolve/lib/ModulesInDirectoriesPlugin.js:54:23

My dependencies in package.json are as follows:

> "dependencies": {
>     "altered.js": "^0.8.6",
>     "base-64": "^0.1.0",
>     "immutable": "^3.8.1",
>     "react-tap-event-plugin": "^1.0.0",
>     "roc-package-web-app-react": "^1.0.0-beta.3",
>     "roc-plugin-test-mocha-karma-webpack": "^1.0.0-beta.3"
>   },
>   "devDependencies": {
>     "babel": "^6.5.2",
>     "babel-cli": "^6.7.7",
>     "babel-eslint": "6.0.2",
>     "babel-plugin-transform-decorators-legacy": "^1.3.4",
>     "babel-preset-es2015": "^6.6.0",
>     "babel-preset-react": "^6.5.0",
>     "babel-preset-stage-0": "^6.5.0",
>     "chai": "^3.5.0",
>     "chai-as-promised": "^5.3.0",
>     "chai-immutable": "^1.5.4",
>     "enzyme": "^2.3.0",
>     "eslint": "2.6.0",
>     "eslint-config-airbnb": "6.2.0",
>     "eslint-plugin-react": "4.2.3",
>     "ignore-styles": "^4.0.0",
>     "interact.js": "^1.2.6",
>     "isomorphic-fetch" : "^2.2.1",
>     "marked": "^0.3.5",
>     "moment": "^2.15.1",
>     "react-addons-test-utils": "^15.1.0",
>     "react-calendar-timeline": "git+https://git@bitbucket.org/jamaku/timeline.git",
>     "react-date-picker": "^5.3.28",
>     "react-dnd": "^2.1.4",
>     "react-dnd-html5-backend": "^2.1.2",
>     "react-scroll": "^1.4.0",
>     "roc-package-web-app-react-dev": "^1.0.0-beta.3",
>     "roc-plugin-style-sass": "^1.0.0-beta.3",
>     "trepanjs": "^0.2.5"
>   }

In another folder the same project (where the last **npm install** was done some days ago) builds on Roc with no issues whatsoever, so my bet would be on internal dependencies issue rather than something I did with my setup?

**Comment by dlmr** [comment]
The reason for this is that React has been updated to `15.4` and Roc trusts that React follows SemVer correctly, that means that minor version should not introduce breaking changes. 

This update did however change some things internally in React which resulted in breaking some instances where code used private APIs. This is something that `react-tap-event-plugin` does and it is the most likley reason why this happens. This have now been addressed in it and updating it to the latest version should fix the issue you are having.

**Reinstalling `react-tap-event-plugin`**

```
npm install --save react-tap-event-plugin
```

**Comment by dorota-jking** [comment]
OK, that seems to have fixed it. Thanks for your explanation and swift help!!!
