### ISSUE TITLE
error installing a local template

### ISSUE THREAD

**Issue by andreasgrimm** [rocjs/roc#157]
roc version: 1.0.0-rc.10

adhering to https://github.com/rocjs/roc/blob/master/docs/Templates.md#local-template I tried to install a local template. Here's what I did plus error message:

```shell
 template-test> roc init ../../roc-template-my-template

Found a folder named /foo/bar/template-test, will try to use it.


An error occured during init!

Unexpected token < in JSON at position 0 in "https://api.github.com/repos/../../roc-template-my-template/tags":
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="...
```

(slightly) OT: any plans on supporting private github repos directly?

**Comment by dlmr** [comment]
The documentation that we have is for the `next` version of Roc, that is versions after `1.0.0-rc.10`, that soon will become the first stable version of Roc. The reason that we have it behind the `next` tag is that it is a breaking change from `1.0.0-rc.10`.

You can install this version using `npm install roc@next`.

> (slightly) OT: any plans on supporting private github repos directly?

You should be able to install from a private repo as mentioned [here](https://github.com/rocjs/roc/blob/master/docs/Templates.md#generic-git).

**Comment by andreasgrimm** [comment]
using roc version `next` now works like a charm.
I guess I didn't look close enough when initially npm-installing it.

Thanks so much for pointing out!
