### ISSUE TITLE
Should we always add the calling module to the CLI

### ISSUE THREAD

**Issue by dlmr** [rocjs/roc#16]
With the current structure in #12 it is possible to use a CLI defined in for example `roc-web-react` but not use anything that it provides. There is no real point to this since we should aim for that all Roc packages have their own CLI that can be used. So the question is if we should always add the module that the user uses for the CLI or if this behaviour should be ok.

This also mean that a user could say that the no extensions should be used meaning that the CLI will be pointless. In this case should we add the module itself, give information about that there is no extensions active or do nothing.

We need to think about how we can solve this in the best way before releasing v1.0.

**Comment by andreasrs** [comment]
Closing issue. We will fix this (and related potential for confusion) with the merge of roc and roc-config. All packages will have a dependency on that module and hence use the same cli. As discussed around this issue in person, we must aim to avoid confusion around these things and so far this is the best way to go about it without losing flexibility.
