### ISSUE TITLE
Roc replaces non-existing template variables with empty string

### ISSUE THREAD

**Issue by pmrukot** [rocjs/roc#169]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Reference: https://github.com/rocjs/roc/blob/master/docs/Templates.md#templates-1
Currently `roc` replaces every text inside template files that is surrounded by double curly braces, even if the variable inside the braces is not specified in `roc.setup.json`. For example, lets have following `roc.setup.json`:
```javascript
{
  "prompts": {
    "name": {
      "type": "string"
    },
    "description": {
      "type": "string"
    }
  }
}
```
All the text inside template files that is `{{name}}` or `{{description}}` will be replaced with provided variables. But if there is something that is not specified in `roc.setup.json` it would replace it anyway, with empty string (at least it seems like empty string). For example if I had something like `someExampleString: {{nonExisingVariable}}` in one of my files, roc would replace it to `someExampleString: `.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal example.**
Create `roc template` structure according to docs: https://github.com/rocjs/roc/blob/master/docs/Templates.md#templates-1
Add some variables in `roc.setup.json`, add them to your template files but also add some that do not exist.
Generate project using template you created using `roc new ./path_to_template`.
Roc will replace non existing variables with empty strings.

**What is the expected behavior?**
Roc should leave all the variables that are not specified untouched.

**Afterthougts**
I was thinking about syntax that could be better than double curly braces, since it's quite common in js world, for example in handlebars or angular. Since `roc` seems to be used mainly in react that is not quite a big problem but still.
Also I guess many templates are currently using that syntax so changing it might be quite hard.

**Comment by fix-fix** [comment]
I don't see how this is a bug, it's just a normal behaviour of Handlebars, you can see it defined in the [tests](https://github.com/wycats/handlebars.js/blob/714a4c448281aef44bcafc4d9e4ecf32ed063b8b/spec/basic.js#L30). Perhaps it's not documented clearly that templates are processed by Handlebars.

If you want to keep some expressions intact, just escape them like so: `\{{nonExisingVariable}}`

It would be really helpful to warn about undefined variables, but as far as I know there is no way to get that info from Handlebars.

**Comment by dlmr** [comment]
Good point @fix-fix, will go ahead and close this and we can come back to it later if we want to add some type of warning message or similar down the road.
