### ISSUE TITLE
Status of roc

### ISSUE THREAD

**Issue by kschulst** [rocjs/roc#174]
Hi, just wanted to know what the future plans for roc are? Seems like there haven't been a lot of activity on this project lately. Seems like a very promising tool, but afraid to commit to it if it is being abandoned.

**Comment by dlmr** [comment]
Hello! 👋 

Roc is alive and well and the commitment to the project is still strong with broad adoption within Schibsted, and steadily increasing over time. This may not be well reflected in the core Roc repo however, something we should look into making more clear perhaps.

Despite that the project progression have been a little slow recently, our roadmap and plans include features that will further strengthen Roc in the coming future, so watch this space. 

With that said, Roc currently works great for several projects within and outside of Schibsted, so this does not need to be a reason for concern. 🙂

**Comment by Reasonable-Solutions** [comment]
@kschulst I work with roc based projects on a daily basis. It's amazing. -Just works- .
