### ISSUE TITLE
Eslint error: 'dependency' should be listed in the project's dependencies

### ISSUE THREAD

**Issue by wadim** [rocjs/roc#175]
### Background

When I generate a new roc project I see that `eslint` picks up a lot of errors similar to the one below:

<img width="479" alt="screen shot 2017-05-15 at 11 04 10" src="https://cloud.githubusercontent.com/assets/941978/26051279/fd4b8e86-3961-11e7-9b80-f2629287a681.png">

My understanding of this problem is that this is a result of `roc`'s design choices: `roc` takes over the responsibility of handling such dependencies for me: my project no longer _depends on_ `react`, it _depends on_ `roc` and `roc` _depends on_ `react`.

However, since `eslint` is a stage of my CI process, I cannot have any `eslint` errors in my code.

### Questions

1. How would you recommend solving this?
2. Is adding the roc dependencies as `peerDependencies` in my project a good solution?
3. Can this be done automatically by `roc` so I don't have to do it manually each time?

**Comment by fix-fix** [comment]
It should be solved by writing custom resolver for `eslint-plugin-import` (or maybe just using `eslint-import-resolver-webpack`, if it's possible to provide webpack config at runtime), see [docs](https://github.com/benmosher/eslint-plugin-import#resolvers)

**Comment by wadim** [comment]
Thanks @fix-fix! Using `eslint-plugin-import` seems to make much more sense and it seems like the obvious way to go.

Do you have a setup which already works for you?

Using `eslint-import-resolver-webpack` seems like a natural solution (if you're using webpack) but this particular resolver seems to expect a physical `webpack.config.js` file which I don't think exists anywhere other than in-memory during building/development?

It seems that the error which I am getting (`import/no-extraneous-dependencies`) is an error which relates not so much to resolving itself (which works, otherwise the error would be different) but to the module not being declared in `package.json`. **Have you gotten it to work with a custom resolver?** Knowing this would validate my future attempts at writing one. So far I have attempted to "hack" it by using `babel-plugin-module-resolver` and `eslint-import-resolver-babel-module` with the following config:

`.babelrc`:
```
{
  "plugins": [
    ["module-resolver", {
      "root": ["./src/components", "./node_modules"]
    }]
  ]
}
```

`.eslintrc`:
```
...
    "settings": {
      "import/resolver": {
        "babel-module": {}
      }
    }
...
```

This setup gets `eslint` to recognize modules inside of `./src/components` without errors, but it still marks the `import React from 'react';` as erroneous with the same error message: `import/no-extraneous-dependencies`.

**Comment by fix-fix** [comment]
@wadim I don't have any working solution at the moment.

Looking at the [source](https://github.com/benmosher/eslint-plugin-import/blob/bd0e5e3dd5781b125dc02971ddb011aaa554bf4f/src/rules/no-extraneous-dependencies.js#L39) of eslint-plugin-import, it indeed seems like this information is not collected from providers, but taken directly from `package.json`.

In that case I think it's impossible to fix this without changes in eslint-plugin-import.

**Comment by dlmr** [comment]
To support this in an optimal way we need to do as what @fix-fix suggests, creating a `eslint-import-resolver-roc` and probably a `eslint-config-roc` as well. I have thought about doing this myself but never gotten around to it and if someone is up for it I think it would be a great addition to the ecosystem and something I think we could host under this organization. 

To manage this currently I often just either set this rule to a warning or turn it off completely.

With that said, I could not stop myself from giving this some more thought and I now have something you can test in your project @wadim.   

**Note that this is an experiment and should be optimized further in the future if it works.** 

### `.eslintrc`
_Example that uses `eslint-config-airbnb`_
```js
{
  "extends": [
    "eslint-config-airbnb",
    "./eslint-config-roc.js"
  ]
}
```

### `eslint-config-roc.js`
```js
const path = require('path');

// Registers the runtime to be able to read the Roc Context
require('roc/runtime/register');

const context = require('roc/lib/context/helpers/manageContext').getContext();
const coreModules = Object.keys(context.dependencies.exports);

module.exports = {
  settings: {
    'import/resolver': path.resolve('./eslint-import-resolver-roc'),
    // Uses core-modules here to make eslint-plugin-import not complain about dependencies
    // missing from package.json - the only way to manage this today
    'import/core-modules': coreModules
  }
};
```

### `eslint-import-resolver-roc.js`
```js
const path = require('path');
const resolver = require('roc').getResolveRequest('eslint-plugin-import');

const resolve = require('resolve');

module.exports.interfaceVersion = 2;

module.exports.resolve = function eslintImportResolver(source, file) {
  const context = path.dirname(path.resolve(file));

  if (resolve.isCore(source)) {
    return { found: true, path: null };
  }

  try {
    return {
      found: true,
      path: resolve.sync(resolver(source, context), { basedir: context })
    };
  } catch (err) {
    /* ignore this error and try again instead with fallback enabled */
  }

  try {
    return {
      found: true,
      path: resolve.sync(resolver(source, context, true), { basedir: context })
    };
  } catch (err) {
    return { found: false };
  }
};
```

**Comment by krzysztofslonka** [comment]
What is the status on this?

**Comment by dlmr** [comment]
I have now published this a module on npm.

https://github.com/rocjs/eslint-roc/tree/master/packages/eslint-config-roc
