### ISSUE TITLE
How to pass `--inspect` option to node

### ISSUE THREAD

**Issue by GabrielDelepine** [rocjs/roc#198]
Hi

I looking for the proper option to use the `--inspect` mode of node to be able to debug server-side

Thanks

**Comment by dlmr** [comment]
Hi!

This is what I would do.

```
node --inspect node_modules/.bin/roc start
```
https://github.com/rocjs/roc/blob/master/docs/Runtime.md#start-the-application-using-the-command-line-script-manually

**Comment by GabrielDelepine** [comment]
Wonderful, thanks!
