### ISSUE TITLE
Remove Codacy since it's not representativ

### ISSUE THREAD

**Issue by dlmr** [rocjs/roc#40]
Codacy does not handle ES6 and gives a lot of false positives. I suggest that we disable it on our PR.
What do you think @andreasrs @androa?

**Comment by dlmr** [comment]
Apparently they now support ES6 but it seems to not be automatically detected and might require som configuration. http://blog.codacy.com/2015/12/21/codacy-integrates-with-eslint/

**Comment by andreasrs** [comment]
Codacy removed from Roc projects.
