### ISSUE TITLE
Improve templates

### ISSUE THREAD

**Issue by dlmr** [rocjs/roc#75]
_This issue will serve a documentation place for things that we want to do in relation to templates._
_Please comment with additional things that we should investigate/add._
### More power after template install

Currently after a template has been instantiated a `completionMessage` can be show to the user. It would be beneficial if this was not only a string as it is now but that it also could be a function/command that can run and do additional things. 

For instance it could automatically build the new project and start it in development mode.

**Comment by Naycon** [comment]
### Support for conditionals in templates

One thing that could come in handy when creating templates could be to be able to conditionally add files or lines in a file. An example of a use case could be to add support for choosing whether to use css, sass, less or stylus for styles. Another use case could be to prompt the user for which editor that is being used. The answer could then be used to add editor config files and then conditionally add them to .gitignore as well.

**Comment by dlmr** [comment]
This has been solved in #115 

We should create new issues if more needs arises.
