### ISSUE TITLE
Support for windows

### ISSUE THREAD

**Issue by glennerik** [rocjs/roc#91]
At DM1881 I have to use windows.
Even tough I'm using roc in Vagrant right now,
I'd love it if it was possible to roc dev on windows

**Comment by dlmr** [comment]
Thanks for filing this issue! This is something we very much would like to support but unfortunately something we don’t have time for at the immediate moment. We promise however to get back to this as soon as possible and contributes forwards this in the mean time are encouraged.

**Comment by insin** [comment]
https://github.com/IndigoUnited/node-cross-spawn fixes common spawning issues on Windows

**Comment by schibsted-martin** [comment]
+1

Tagging since I am interested (and will be using rocjs very soon). @insin Is your PR supposed to fix the issue when creating a new project? I just installed roc and ran the command and got the output:

```
>roc new roc-test web-app-react
Using v1.0.3 as template version

Installing template setup dependencies…
Error: spawn npm ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

As far as I can tell your PR to use cross-spawn is already merged; so this is a new error or do I need to fix something else?

Depending on your answer I will attempt to help out with PR's for Windows; we need to fight for our right to code :)

**Comment by dlmr** [comment]
The PR is merged to master but no new release has yet been done that includes the fix. The reason for this is that there is more things that needs to be updated before Roc supports Windows fully. 

I will try to formalize the list I have of things that needs to be fixed as soon as possible making it easier for others to contribute.

**Comment by schibsted-martin** [comment]
@dlmr Great, thanks! I will download the source and try to run it from master directly and see if I can help out with any area.

I assume that the community would accept that Windows support would be a little shaky in the early stages; as long as the bigger flows work. As long as you can work with an app that has been created with roc I am happy.

Looking forward to seeing what comes next.

## Edit

I apologize for asking maybe a basic question here; but I am a bit new to github projects and PR's etc.
Anyway, I performed the following steps to set up roc locally to be able to help out, could you please verify if it is the correct way of doing it?
- I had done a `npm i -g roc` before; and I did not uninstall it.
- I did a `git clone`
- Ran `npm i` in the roc root folder
- Ran `npm link`
- Assumed that the "global roc reference" would be the one of the repository that I just downloaded

Having done these steps I was able to create a new roc app using the following commands from a different folder all together:

```
>roc new roc-test2 web-app-react
Using v1.0.3 as template version

Installing template setup dependencies…

> roc@1.0.0-rc.9 postinstall %HOMEPATH%\AppData\Local\Temp\roc116412-12132-4o9spp\node_modules\roc
> node ./scripts/post-install.js

roc-template-web-app-react@1.0.0 %HOMEPATH%\AppData\Local\Temp\roc116412-12132-4o9spp
+-- chalk@1.1.3
... (lots of dependencies)
    `-- semver-diff@2.1.0

? What's the name of your application? roc-test
? What's the description for the application? Testing roc on Windows
? Who's the author of the application? Me
? What's the license for the application? MIT
? What's the port for the application? 3030
? What do you what to use for <title>? Testing roc on Windows

Installing template dependencies… (If this fails you can try to run npm install directly)

> node-sass@3.4.2 install %HOMEPATH%\Desktop\roc-test2\node_modules\node-sass
> node scripts/install.js

Binary downloaded and installed at %HOMEPATH%\Desktop\roc-test2\node_modules\node-sass\vendor\win32-x64-46\binding.node

> spawn-sync@1.0.15 postinstall %HOMEPATH%\Desktop\roc-test2\node_modules\spawn-sync
> node postinstall


> roc@1.0.0-rc.9 postinstall %HOMEPATH%\Desktop\roc-test2\node_modules\roc
> node ./scripts/post-install.js


> node-sass@3.4.2 postinstall %HOMEPATH%\Desktop\roc-test2\node_modules\node-sass
> node scripts/build.js

` %HOMEPATH%\Desktop\roc-test2\node_modules\node-sass\vendor\win32-x64-46\binding.node ` exists.
 testing binary.
Binary is fine; exiting.
roc-test@1.0.0 %HOMEPATH%\Desktop\roc-test2
+-- babel-eslint@6.0.2
... (even more dependencies)
      `-- source-map@0.4.4


Setup completed!

Start in development mode by running roc dev.
It will open your default browser when ready.
You can change this by setting dev.browsersync.open to false in roc.config.js.
```

I get some errors running `roc dev` inside the app folder but at least it installed the app! :+1:

**Comment by dlmr** [comment]
@schibsted-martin That is correct and exactly how we do it as well!
